spring:
  mvc:
    validation:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/asset-manager
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
jwt:
  secret-key: ${JWT_SECRET_KEY}
