spring:
  mvc:
    validation:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESS_URL}
    username: ${POSTGRESS_USERNAME}
    password: ${POSTGRESS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
jwt:
  secret-key: ${JWT_SECRET_KEY}
